### ISSUE TITLE
D-link DIR-816 A2_v1.10CNB04.img固件模拟问题

### ISSUE THREAD

**Issue by Marchibun** [z1r00/IOT_Vul#1]
您好，
我使用firmAE模拟D-link DIR-816 A2_v1.10CNB04.img这一固件时, 只有命令行接口起来了，但web接口却始终不能正常连接，请问您是如果模拟起来的呢？
或者能把您的虚拟机发给我吗？
945595591@qq.com

**Comment by z1r00** [comment]
> 您好，我用公司AE模拟DIR-816 A2_v1-link DIR-816 A2_v1.DIR -816 A2_v110CNB04.gg的时候，就可以立即接口呢，但是网络不能正常连接吗？把你的虚拟机发给我吗？ [945595591@qq.com](mailto:945595591@qq.com)
您好，我这里直接用的是实体路由器，固件模拟可能需要patch一些东西。

**Comment by futrai778** [comment]
哥/goform/form2systime.cgi这个对应的文件路径是在哪个位置我解压出来的固件里面一直找不到这个文件的位置 ![image](https://user-images.githubusercontent.com/69702233/191710828-e584b3da-9c0a-482e-b6d3-906ab2a304a4.png)

**Comment by z1r00** [comment]
> 哥/goform/form2systime.cgi这个文件的路径是在哪个位置，我解压出来的一直坚持找不到这个文件的位置![图片](https://user-images.githubusercontent.com/69702233/191710828-e584b3da-9c0a-482e-b6d3-906ab2a304a4.png)

/goform/form2systime.cgi这个是开发者自己写的，具体在/bin/goahead这个文件中实现

**Comment by futrai778** [comment]
> > 哥/goform/form2systime.cgi这个文件的路径是在哪个位置，我解压出来的一直坚持找不到这个文件的位置![图片](https://user-images.githubusercontent.com/69702233/191710828-e584b3da-9c0a-482e-b6d3-906ab2a304a4.png)
> 
> 
> 
> /goform/form2systime.cgi这个是开发者自己写的，具体在/bin/goahead这个文件中实现

goform/editassignment那像这种的话也是统一在bin/goform里面实现的嘛

**Comment by z1r00** [comment]
> > > 哥/goform/form2systime.cgi这个文件的路径是在哪个位置，我解压出来的一直坚持找不到这个文件的位置![图片](https://user-images.githubusercontent.com/69702233/191710828-e584b3da-9c0a-482e-b6d3-906ab2a304a4.png)
> > 
> > 
> > /goform/form2systime.cgi这个是开发者自己写的，具体在/bin/goahead这个文件中实现
> 
> goform/editassignment那像这种的话也是统一在bin/goform里面实现的嘛

对的可以看一下笔者写过的入门文章https://iotsec-zone.com/article?id=211里面有详细介绍

**Comment by futrai778** [comment]
> > > > 哥/goform/form2systime.cgi这个文件的路径是在哪个位置，我解压出来的一直坚持找不到这个文件的位置![图片](https://user-images.githubusercontent.com/69702233/191710828-e584b3da-9c0a-482e-b6d3-906ab2a304a4.png)
> 
> > > 
> 
> > > 
> 
> > > /goform/form2systime.cgi这个是开发者自己写的，具体在/bin/goahead这个文件中实现
> 
> > 
> 
> > goform/editassignment那像这种的话也是统一在bin/goform里面实现的嘛
> 
> 
> 
> 对的可以看一下笔者写过的入门文章https://iotsec-zone.com/article?id=211里面有详细介绍

感谢老哥解惑

**Comment by futrai778** [comment]
> > 您好，我用公司AE模拟DIR-816 A2_v1-link DIR-816 A2_v1.DIR -816 A2_v110CNB04.gg的时候，就可以立即接口呢，但是网络不能正常连接吗？把你的虚拟机发给我吗？  [945595591@qq.com ](mailto:945595591@qq.com)
> > 您好，我这里直接用的是实体路由器，固件模拟可能需要patch一些东西。

![图片](https://user-images.githubusercontent.com/69702233/192480359-e1335697-2262-4a9a-b92d-c173fe3d5e61.png)
用pwngdb来调试goform文件一报错

**Comment by z1r00** [comment]
> > > 您好，我用公司AE模拟DIR-816 A2_v1-link DIR-816 A2_v1.DIR -816 A2_v110CNB04.gg的时候，就可以立即接口呢，但是网络不能正常连接吗？把你的虚拟机发给我吗？  [945595591@qq.com ](mailto:945595591@qq.com)
> > > 您好，我这里直接用的是实体路由器，固件模拟可能需要patch一些东西。
> 
> ![图片](https://user-images.githubusercontent.com/69702233/192480359-e1335697-2262-4a9a-b92d-c173fe3d5e61.png) 用pwngdb来调试goform文件一报错

goahead是mips32的架构，需要进行qemu模拟，然后使用gdb-multiarch进行调试
