### ISSUE TITLE
在goahead里面找不到addassignment函数

### ISSUE THREAD

**Issue by futrai778** [z1r00/IOT_Vul#2]
![图片](https://user-images.githubusercontent.com/69702233/193532344-2726086b-311c-4024-aa9f-47b2e6924d86.png)

**Comment by z1r00** [comment]
> ![图片](https://user-images.githubusercontent.com/69702233/193532344-2726086b-311c-4024-aa9f-47b2e6924d86.png)

这个是我自己命名的，需要在form处理的功能里面找一下
