### ISSUE TITLE
D-link DIR-816 A2_v1.10CNB04.img share

### ISSUE THREAD

**Issue by whitepoet** [z1r00/IOT_Vul#3]
不好意思，我无法在网上找到D-link DIR-816 A2_v1.10CNB04.img的固件，不知道您那里是否还有保留，能否发给我，十分感谢！
邮箱是zjxu_R@outlook.com

**Comment by z1r00** [comment]
> 不好意思，我无法在网上找到D-link DIR-816 A2_v1.10CNB04.img的固件，不知道您那里是否还有保留，能否发给我，十分感谢！ 邮箱是[zjxu_R@outlook.com](mailto:zjxu_R@outlook.com)

已经发你
