### ISSUE TITLE
关于 D-link DIR-816 A2_v1.10CNB04.img 固件

### ISSUE THREAD

**Issue by NarutoGit** [z1r00/IOT_Vul#5]
您好，由于在网上一直没有找到 D-link DIR-816 A2_v1.10CNB04.img 的固件，就冒昧打扰了，如果您还有保存，不知是否方便发我一下， 
 allinnow0.0@gmail.com  ， 非常感谢~~

**Comment by z1r00** [comment]
https://github.com/z1r00/IOT_Vul/blob/main/%E5%9B%BA%E4%BB%B6%E4%B8%8B%E8%BD%BD/DIR-816%20A2_v1.10CNB04.img

**Comment by NarutoGit** [comment]
太感谢您啦
